name: tinytuner
description: "A Tiny Tuner project."
version: 0.2.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^9.0.0
  permission_handler: ^11.4.0
  record: ^6.1.2
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
